### ISSUE TITLE
Status of the CL deep learning library: development, etc? How to react you

### ISSUE THREAD

**Issue by jeosol** [chunsj/TH#1]
Hi Chun,

This is not an issue per se, but I didn't see your email address on how to reach you. 

I am also interested in deep learning using common lisp. I am coming from a bit of tensorflow with python. I have started working on a simple deep learning library and testing with one hidden layer. I am implemented everything from scratch but someone recently pointed me to your library which is much further ahead. 

What is the status of the library, in terms of continued development efforts and work on it. Also, do you have other developers? Are there licence restrictions at this time? Are you benchmarking with some of the public datasets and other framework librariers. 

If you can send your email address, we can have conversation outside of github. 

Cheers

**Comment by chunsj** [comment]
First, thank you for the interest.

1. Current status of the library - the latest version of TH is in the bitbucket (https://bitbucket.org/chunsj/th/src/master/) - in a word is that as far as I know, the library has only one user, me, and I have been using this in my work. I will keep working on this library at least more than one or two years.

2. No, there's no other developer.

3. The library has GPL3 license.

4. No, other than simple MNIST or something similar to that of kinds, I have not yet performed benchmarks.

My original intention of this library is building a binding for libTH (C library part of the original torch written in lua) and has been a nice experience at least to me. Most of my usage patterns are regression/classification (mostly linear, sometimes nn), and linear algebra related. So if you are finding ready-to-use, builtin-models, then this is not what you want.

The biggest problem in TH is that it depends on libTH which is almost dead. (And I'm not such a good lisp programmer :-P)

**Comment by jeosol** [comment]
Thank you for your reply. 

I admit I was not aware of libTH (ony focused onTensorflow and Torch). While I do have interest in an interface in Common Lisp to call these libraries for now, I am using Python Tensorflow/Keras. It will be a serious effort to be able to replicate these libraries/interfaces on the CL side and will need some dedicated devs for sure. 

You put together the library and it works for you so may be you a good lisper. It's good it's working for you. The main issue is the libTH part you mentioned and that it is not seeing much development. But if it works for you that's great so far.
