### ISSUE TITLE
TODOS 3 (possible solutions ?)

### ISSUE THREAD

**Issue by anranyicheng** [chunsj/TH#4]
TODOS
 3.Find why using Accelerator.framework makes geev emits floating point overflow error.

I found a discussion group with a similar problem, but I am not familiar with OpenBLAS at the moment, I know you are familiar with this library, I hope it can help you find the cause of the problem, I look forward to your response, thank you!  https://github.com/quil-lang/magicl/issues/62

**Comment by chunsj** [comment]
It seems that you have found an important key for this problem. I could investigate this problem in this weekend if things would be going well. This almost surely is related to the TH binding where the geev call is bound.

**Comment by chunsj** [comment]
Though I haven't tried this (busy in IRL), this is the solution of the problem.
