### ISSUE TITLE
where can i install your mu library?

### ISSUE THREAD

**Issue by vajrabisj** [chunsj/TH#5]
did not find the link to the mu library...

**Comment by chunsj** [comment]
My additional libraries or dependencies are located at bitbucket.org. MU is
at
https://bitbucket.org/chunsj/mu/src/master/
 as well as the latest version of TH.

**Comment by vajrabisj** [comment]
Thanks for prompt reply. But after clone all your git and the lint, and also copied those libTHNeural.0.so, libTHTensor.0.so to the /use/local/lib, after load in CL, there is still error on cannot open the lib files…

**Comment by chunsj** [comment]
You can ldd on the library files, for example;
$ ldd libTHTensor.0.so
to see which additional libraries are needed. Or, you can build from the source files.
https://bitbucket.org/chunsj/libth/src/master/
You can use GNUmakefile.linux.i5 as a starting point. (sorry for multiple, reduandant
makefiles)
